### PR TITLE
Fix install and running of example scripts

### LINKED ISSUE #98: Scripts in `examples` don't work out of the box
There is a bug in the scripts in the examples folder. The install instructions are also not correct.

- Variable `url` shadows package `url`.
- Install instructions assume published couchbackup 2.0.0.

### PR DESCRIPTION
**Pull request by mikerhodes**
Fixes the minor bugs in the scripts in `examples`.

Fixes #98

### CODE REVIEW

File: examples/s3-backup-file.js [hunk 1]
```diff
@@ -182,8 +182,8 @@ function uploadNewBackup(s3, backupTmpFilePath, bucket, key) {
  *
  * @param {string} url URL to safen
  */
-function s(url) {
-  var parts = url.parse(url);
+function s(originalUrll) {
```
Comment (ricellis) [inline examples/s3-backup-file.js]: originalUrll -> originalUrl

File: examples/s3-backup-file.js [hunk 2]
```diff
@@ -182,8 +182,8 @@ function uploadNewBackup(s3, backupTmpFilePath, bucket, key) {
...
+  var parts = url.parse(originalUrll);
```
Comment (ricellis) [inline examples/s3-backup-file.js]: and again

File: examples/package.json [hunk 3]
```diff
@@ -4,7 +4,6 @@
   "description": "Examples of using CouchBackup as a library",
   "dependencies": {
     "aws-sdk": "^2.39.0",
-    "couchbackup": "^2.0.0",
```
Comment (ricellis) [inline examples/package.json]: Without this dependency here does the `require` statement need to be updated to point to the local file or it will it safely pick it up from the local `node_modeules` ahead of any globally installed copy?

Comment (mikerhodes) [inline examples/package.json]: It picked it up for me from node_modules after `npm install ../`. I guess it's probably possible to just require the library directly, but didn't think of it before now.

File: examples/s3-backup-file.js (hunk 2 above)
Comment (mikerhodes) [inline examples/s3-backup-file.js]: Bah. This is an infuriating bug/behaviour of the VSCode vim plugin.
