### PR TITLE
Terminate on spool changes failure

### LINKED ISSUE #103: Return bad exit code if backup changes request fails
_Repro:_
```
$ couchbackup --url http://localhost:3000 --db animaldb
================================================================================
Performing backup on http://localhost:3000/animaldb using configuration:
{
  "bufferSize": 500,
  "log": "/var/folders/5p/11lmsvwn5l91cn7ysrs4nm1r0000gn/T/tmp-177433vPdnmpsoMcK.tmp",
  "mode": "full",
  "parallelism": 5
}
================================================================================
Streaming changes to disk:
error { error: 'toxy injected error' }  <-- /_changes request returns 500 here

  couchbackup:backup finished { total: 0 } +0ms
$ echo $?
0
```

### PR DESCRIPTION
**Pull request by smithsz**
## What
Terminate on spool changes failure, for example:
```
$ couchbackup --url http://localhost:3000/ --db animaldb
================================================================================
Performing backup on http://localhost:3000/animaldb using configuration:
{
  "bufferSize": 500,
  "log": "/var/folders/5p/11lmsvwn5l91cn7ysrs4nm1r0000gn/T/tmp-79048fCiWkfAJefLd.tmp",
  "mode": "full",
  "parallelism": 5
}
================================================================================
Changes request failed with status code 500
$ echo $?
30
```

## How
Ensure `resp.statusCode == 200` prior to processing changes body.

## Issues
Fixes #103.

### CODE REVIEW

File: includes/spoolchanges.js [hunk 1]
```diff
@@ -71,18 +67,23 @@ module.exports = function(dbUrl, log, bufferSize, callback) {
...
       processBuffer(true);
       logStream.write(':changes_complete ' + lastSeq + '\n');
       logStream.end();
       console.error('');
-      if (doccount === 0) {
-        callback(new Error('zero documents found - nothing to do'), null);
-      } else {
-        callback(null, {batches: batch, docs: doccount});
-      }
+      callback();
```
Comment (tomblench) [inline includes/spoolchanges.js]: Do we still need the `doccount === 0` check? I guess the only case where this can now happen is on an empty database. Even so it should probably just print a warning rather than throwing an error.

File: includes/spoolchanges.js [hunk 2]
```diff
@@ -71,18 +67,23 @@ module.exports = function(dbUrl, log, bufferSize, callback) {
...
   };
-  client(r)
-    .pipe(liner())
+  var c = client(r);
+  c.end();
+
+  c.on('response', function(resp) {
+    if (resp.statusCode !== 200) {
+      c.abort();
+      callback(new error.BackupError('SpoolChangesError', 'Changes request failed with status code ' + resp.statusCode));
```
Comment (tomblench) [inline includes/spoolchanges.js]: You can use the fancy interpolation style here using backticks

Comment (smithsz) [inline includes/spoolchanges.js]: ooh, will do

File: includes/spoolchanges.js (hunk 1 above)
Comment (smithsz) [inline includes/spoolchanges.js]: Nothing is looking at the err in that callback in master currently. It just gets ignored. So these changes don't affect behaviour.
I don't think having 0 docs in your db is an error anyway. So I'm suggesting we get rid of the `doccount` check.

_Backing up an empty db:_
```
$ couchbackup --url https://samsmith.cloudant.com --db newdb1
================================================================================
Performing backup on https://****:****@samsmith.cloudant.com/newdb1 using configuration:
{
  "bufferSize": 500,
  "log": "/var/folders/5p/11lmsvwn5l91cn7ysrs4nm1r0000gn/T/tmp-34812WgkPowX4hEdx.tmp",
  "mode": "full",
  "parallelism": 5
}
================================================================================
Streaming changes to disk:

couchbackup:backup finished { total: 0 } +0ms
$ echo $?
0
```
